spring:
  jpa:
    show-sql: true

server:
  error:
    include-stacktrace: always

jwt:
  access-expire: 3600000
  refresh-expire: 1209600000

logging:
  level:
    org.springframework.web.servlet: DEBUG
    org.springframework.web.method.annotation: TRACE
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
    com.plateapp.plate_main.friend: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
