package com.plateapp.plate_main.admin.seasonal.controller;import com.plateapp.plate_main.admin.common.AdminPageResponse;import com.plateapp.plate_main.admin.seasonal.dto.SeasonalCurationDtos.*;import com.plateapp.plate_main.admin.seasonal.service.SeasonalCurationService;import com.plateapp.plate_main.admin.security.*;import com.plateapp.plate_main.auth.security.PlateAuthorities;import com.plateapp.plate_main.common.api.ApiResponse;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import java.util.List;import lombok.RequiredArgsConstructor;import org.springframework.security.access.AccessDeniedException;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/admin/seasonal-curations") @RequiredArgsConstructor
public class SeasonalCurationController{private final SeasonalCurationService service;private final AdminActorResolver actors;
 @GetMapping public ApiResponse<AdminPageResponse<Response>>list(Authentication a,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String status){read(a);return ApiResponse.ok(service.list(page,size,status));}
 @PostMapping public ApiResponse<Response>create(@Valid @RequestBody UpsertRequest c,Authentication a,HttpServletRequest r){write(a);return ApiResponse.ok(service.create(c,actors.resolve(a),r));}
 @GetMapping("/{id}")public ApiResponse<Response>detail(@PathVariable Long id,Authentication a){read(a);return ApiResponse.ok(service.detail(id));}
 @PutMapping("/{id}")public ApiResponse<Response>update(@PathVariable Long id,@Valid @RequestBody UpsertRequest c,Authentication a,HttpServletRequest r){write(a);return ApiResponse.ok(service.update(id,c,actors.resolve(a),r));}
 @DeleteMapping("/{id}")public ApiResponse<Void>delete(@PathVariable Long id,@RequestParam Long version,Authentication a,HttpServletRequest r){write(a);service.delete(id,version,actors.resolve(a),r);return ApiResponse.ok();}
 @PatchMapping("/order")public ApiResponse<List<Response>>order(@Valid @RequestBody OrderRequest c,Authentication a,HttpServletRequest r){write(a);return ApiResponse.ok(service.reorder(c,actors.resolve(a),r));}
 @PostMapping("/{id}/publish")public ApiResponse<Response>publish(@PathVariable Long id,@Valid @RequestBody PublishRequest c,Authentication a,HttpServletRequest r){write(a);return ApiResponse.ok(service.publish(id,c,actors.resolve(a),r));}
 private void read(Authentication a){if(!PlateAuthorities.hasAdminPermission(a,PlateAuthorities.PERMISSION_SEASONAL_READ))throw new AccessDeniedException("SEASONAL_READ required");}private void write(Authentication a){if(!PlateAuthorities.hasAdminPermission(a,PlateAuthorities.PERMISSION_SEASONAL_MANAGE))throw new AccessDeniedException("SEASONAL_MANAGE required");}
}
