package com.plateapp.plate_main.admin.feedmoderation.controller;
import com.plateapp.plate_main.admin.common.AdminPageResponse;import com.plateapp.plate_main.admin.feedmoderation.dto.AdminFeedDtos.*;import com.plateapp.plate_main.admin.feedmoderation.service.AdminFeedService;import com.plateapp.plate_main.admin.security.*;import com.plateapp.plate_main.auth.security.PlateAuthorities;import com.plateapp.plate_main.common.api.ApiResponse;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import org.springframework.security.access.AccessDeniedException;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/admin/feeds") @RequiredArgsConstructor
public class AdminFeedController {private final AdminFeedService service;private final AdminActorResolver actors;
 @GetMapping public ApiResponse<AdminPageResponse<Response>> list(Authentication a,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String keyword,@RequestParam(required=false)String visibility,@RequestParam(required=false)Boolean recommended){read(a);return ApiResponse.ok(service.list(page,size,keyword,visibility,recommended));}
 @GetMapping("/{id}")public ApiResponse<Response> detail(@PathVariable Integer id,Authentication a){read(a);return ApiResponse.ok(service.detail(id));}
 @GetMapping("/{id}/reports")public ApiResponse<AdminPageResponse<ReportResponse>> reports(@PathVariable Integer id,Authentication a,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){read(a);return ApiResponse.ok(service.reports(id,page,size));}
 @PostMapping("/{id}/hide")public ApiResponse<Response> hide(@PathVariable Integer id,@Valid @RequestBody ActionRequest c,Authentication a,HttpServletRequest r){write(a);return ApiResponse.ok(service.visibility(id,c,false,actors.resolve(a),r));}
 @PostMapping("/{id}/restore")public ApiResponse<Response> restore(@PathVariable Integer id,@Valid @RequestBody ActionRequest c,Authentication a,HttpServletRequest r){write(a);return ApiResponse.ok(service.visibility(id,c,true,actors.resolve(a),r));}
 @PatchMapping("/{id}/recommendation")public ApiResponse<Response> recommendation(@PathVariable Integer id,@Valid @RequestBody RecommendationRequest c,Authentication a,HttpServletRequest r){write(a);return ApiResponse.ok(service.recommendation(id,c,actors.resolve(a),r));}
 private void read(Authentication a){if(!PlateAuthorities.hasAdminPermission(a,PlateAuthorities.PERMISSION_FEED_READ))throw new AccessDeniedException("FEED_READ required");}private void write(Authentication a){if(!PlateAuthorities.hasAdminPermission(a,PlateAuthorities.PERMISSION_FEED_MODERATE))throw new AccessDeniedException("FEED_MODERATE required");}
}
