package com.plateapp.plate_main.admin.seasonal.service;
import com.plateapp.plate_main.admin.audit.service.AdminAuditService;import com.plateapp.plate_main.admin.common.AdminPageResponse;import com.plateapp.plate_main.admin.seasonal.dto.SeasonalCurationDtos.*;import com.plateapp.plate_main.admin.seasonal.entity.SeasonalCuration;import com.plateapp.plate_main.admin.seasonal.repository.SeasonalCurationRepository;import com.plateapp.plate_main.admin.security.AdminActor;import com.plateapp.plate_main.common.error.*;import com.plateapp.plate_main.restaurant.entity.RestaurantMenu;import com.plateapp.plate_main.restaurant.repository.*;import jakarta.servlet.http.HttpServletRequest;import java.time.*;import java.util.*;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor
public class SeasonalCurationService{private static final Set<String> STATES=Set.of("DRAFT","SCHEDULED","PUBLISHED","ARCHIVED");private final SeasonalCurationRepository repository;private final RestaurantRepository stores;private final RestaurantMenuRepository menus;private final AdminAuditService audit;
 @Transactional(readOnly=true)public AdminPageResponse<Response> list(int page,int size,String status){if(page<0||size<1||size>100)throw invalid("Invalid page or size.");String s=status==null||status.isBlank()?null:status.trim().toUpperCase(Locale.ROOT);if(s!=null&&!STATES.contains(s))throw invalid("Unsupported status.");Pageable p=PageRequest.of(page,size,Sort.by(Sort.Order.asc("displayOrder"),Sort.Order.asc("id")));Page<SeasonalCuration> result=s==null?repository.findAll(p):repository.findByStatus(s,p);return AdminPageResponse.from(result.map(this::map));}
 @Transactional(readOnly=true)public Response detail(Long id){return map(find(id));}
 @Transactional public Response create(UpsertRequest c,AdminActor actor,HttpServletRequest req){validate(c);SeasonalCuration v=repository.saveAndFlush(SeasonalCuration.create(c.title().trim(),trim(c.description()),c.displayOrder(),c.startsAt(),c.endsAt(),safe(c.storeIds()),safe(c.menuIds()),actor.userId()));audit.record(actor,"SEASONAL_CURATION_CREATED","SEASONAL_CURATION",v.getId(),null,Map.of("status",v.getStatus(),"version",v.getVersion()),null,null,req);return map(v);}
 @Transactional public Response update(Long id,UpsertRequest c,AdminActor actor,HttpServletRequest req){if(c.version()==null)throw invalid("version is required.");SeasonalCuration v=findVersion(id,c.version());validate(c);Map<String,Object> prev=Map.of("status",v.getStatus(),"version",v.getVersion());v.update(c.title().trim(),trim(c.description()),c.displayOrder(),c.startsAt(),c.endsAt(),safe(c.storeIds()),safe(c.menuIds()),actor.userId());v=repository.saveAndFlush(v);audit.record(actor,"SEASONAL_CURATION_UPDATED","SEASONAL_CURATION",id,prev,Map.of("status",v.getStatus(),"version",v.getVersion()),null,null,req);return map(v);}
 @Transactional public void delete(Long id,Long version,AdminActor actor,HttpServletRequest req){SeasonalCuration v=findVersion(id,version);repository.delete(v);audit.record(actor,"SEASONAL_CURATION_DELETED","SEASONAL_CURATION",id,Map.of("status",v.getStatus(),"version",v.getVersion()),null,null,null,req);}
 @Transactional public List<Response> reorder(OrderRequest c,AdminActor actor,HttpServletRequest req){Set<Long> ids=new HashSet<>();List<Response> result=new ArrayList<>();for(OrderItem item:c.items()){if(!ids.add(item.curationId()))throw invalid("Duplicate curationId.");SeasonalCuration v=findVersion(item.curationId(),item.version());int before=v.getDisplayOrder();v.reorder(item.displayOrder(),actor.userId());v=repository.saveAndFlush(v);audit.record(actor,"SEASONAL_CURATION_REORDERED","SEASONAL_CURATION",v.getId(),Map.of("displayOrder",before),Map.of("displayOrder",v.getDisplayOrder(),"version",v.getVersion()),null,null,req);result.add(map(v));}return result;}
 @Transactional public Response publish(Long id,PublishRequest c,AdminActor actor,HttpServletRequest req){SeasonalCuration v=findVersion(id,c.version());if("ARCHIVED".equals(v.getStatus()))throw new AppException(ErrorCode.COMMON_CONFLICT,"Archived curation cannot be published.");validateLinks(v.storeIdList(),v.menuIdList());String prev=v.getStatus();v.publish(OffsetDateTime.now(ZoneOffset.UTC));v=repository.saveAndFlush(v);audit.record(actor,"SEASONAL_CURATION_PUBLISHED","SEASONAL_CURATION",id,Map.of("status",prev),Map.of("status",v.getStatus(),"version",v.getVersion()),null,null,req);return map(v);}
 private void validate(UpsertRequest c){if(c.startsAt()!=null&&c.endsAt()!=null&&!c.startsAt().isBefore(c.endsAt()))throw invalid("startsAt must be before endsAt.");validateLinks(safe(c.storeIds()),safe(c.menuIds()));}
 private void validateLinks(List<Long> storeIds,List<Long> menuIds){if(stores.findAllById(storeIds).size()!=new HashSet<>(storeIds).size())throw invalid("One or more stores do not exist.");List<RestaurantMenu> found=menus.findAllById(menuIds);if(found.size()!=new HashSet<>(menuIds).size())throw invalid("One or more menus do not exist.");if(!storeIds.isEmpty()&&found.stream().anyMatch(m->!storeIds.contains(m.getRestaurantId())))throw invalid("Menu does not belong to a linked store.");}
 private SeasonalCuration find(Long id){return repository.findById(id).orElseThrow(()->new AppException(ErrorCode.COMMON_NOT_FOUND));}private SeasonalCuration findVersion(Long id,Long version){SeasonalCuration v=find(id);if(!Objects.equals(version,v.getVersion()))throw new AppException(ErrorCode.COMMON_CONFLICT);return v;}
 private Response map(SeasonalCuration v){return new Response(v.getId(),v.getTitle(),v.getDescription(),v.getStatus(),v.getDisplayOrder(),v.getStartsAt(),v.getEndsAt(),v.storeIdList(),v.menuIdList(),v.getCreatedBy(),v.getUpdatedBy(),v.getCreatedAt(),v.getUpdatedAt(),v.getVersion());}private <T>List<T> safe(List<T> v){return v==null?List.of():v;}private String trim(String s){return s==null||s.isBlank()?null:s.trim();}private AppException invalid(String m){return new AppException(ErrorCode.COMMON_INVALID_INPUT,m);}
}
